export const siteKeywords: string[] = [
  // Core & Short-tail Keywords
  "global jobs",
  "latest jobs",
  "international jobs",
  "remote jobs",
  "work from home jobs",
  "job portal",
  "jobs worldwide",
  "lahore jobs",
  "lahore jobs 2026",
  "islamabad jobs",

  // Intent-based Long-tail Keywords
  "international career opportunities",
  "online hiring listings",
  "remote software engineer jobs",
  "global remote hiring",
  "find jobs abroad",
  "entry level remote jobs",
  "full time remote jobs",

  // Geographic & Category Keywords
  "jobs by country",
  "tech jobs worldwide",
  "it career opportunities",
  "visa sponsorship jobs",

  // Pakistan Jobs
  "pakistan jobs",
  "pakistan jobs 2026",
  "karachi jobs",
  "karachi jobs 2026",
  "rawalpindi jobs",
  "rawalpindi jobs 2026",
  "faisalabad jobs",
  "faisalabad jobs 2026",
  "multan jobs",
  "multan jobs 2026",
  "peshawar jobs",
  "peshawar jobs 2026",
  "quetta jobs",
  "quetta jobs 2026",
  "sialkot jobs",
  "sialkot jobs 2026",
  "gujranwala jobs",
  "gujranwala jobs 2026",
  "hyderabad pakistan jobs",
  "bahawalpur jobs",
  "abbottabad jobs",
  "pakistan private jobs",
  "pakistan online jobs",
  "pakistan career opportunities",
  "jobs in pakistan for graduates",

  // Middle East Jobs
  "dubai jobs",
  "dubai jobs 2026",
  "uae jobs",
  "uae jobs 2026",
  "abu dhabi jobs",
  "abu dhabi jobs 2026",
  "sharjah jobs",
  "qatar jobs",
  "qatar jobs 2026",
  "doha jobs",
  "doha jobs 2026",
  "saudi arabia jobs",
  "saudi arabia jobs 2026",
  "riyadh jobs",
  "riyadh jobs 2026",
  "jeddah jobs",
  "jeddah jobs 2026",
  "kuwait jobs",
  "kuwait jobs 2026",
  "bahrain jobs",
  "bahrain jobs 2026",
  "oman jobs",
  "oman jobs 2026",
  "muscat jobs",
  "muscat jobs 2026",
  "middle east jobs",
  "middle east careers",
  "gulf jobs",
  "gulf career opportunities",

  // International Country Keywords
  "usa jobs",
  "usa jobs 2026",
  "uk jobs",
  "uk jobs 2026",
  "canada jobs",
  "canada jobs 2026",
  "australia jobs",
  "australia jobs 2026",
  "germany jobs",
  "germany jobs 2026",
  "france jobs",
  "france jobs 2026",
  "netherlands jobs",
  "netherlands jobs 2026",
  "ireland jobs",
  "ireland jobs 2026",
  "new zealand jobs",
  "new zealand jobs 2026",
  "singapore jobs",
  "singapore jobs 2026",
  "malaysia jobs",
  "malaysia jobs 2026",
  "japan jobs",
  "japan jobs 2026",
  "south korea jobs",
  "south korea jobs 2026",
  "switzerland jobs",
  "switzerland jobs 2026",
  "sweden jobs",
  "sweden jobs 2026",
  "norway jobs",
  "norway jobs 2026",
  "denmark jobs",
  "denmark jobs 2026",
  "finland jobs",
  "finland jobs 2026",
  "italy jobs",
  "italy jobs 2026",
  "spain jobs",
  "spain jobs 2026",
  "portugal jobs",
  "portugal jobs 2026",
  "poland jobs",
  "poland jobs 2026",
  "europe jobs",
  "european jobs",

  // Remote Work Keywords
  "remote work opportunities",
  "remote career opportunities",
  "remote employment",
  "remote employment opportunities",
  "remote hiring",
  "remote job opportunities",
  "remote positions",
  "remote work jobs",
  "remote jobs worldwide",
  "remote jobs for beginners",
  "remote jobs for graduates",
  "remote jobs for professionals",
  "remote jobs with no experience",
  "remote jobs without experience",
  "remote jobs with flexible hours",
  "flexible remote jobs",
  "work online from home",
  "online work opportunities",
  "online employment opportunities",
  "virtual jobs",
  "virtual work opportunities",
  "home based jobs",
  "home based employment",
  "work from anywhere jobs",
  "work from anywhere opportunities",
  "location independent jobs",
  "distributed team jobs",
  "remote first companies jobs",
  "fully remote positions",
  "hybrid remote jobs",

  // Technology Jobs
  "software developer jobs",
  "software development jobs",
  "software engineer opportunities",
  "web developer jobs",
  "frontend developer jobs",
  "backend developer jobs",
  "full stack developer jobs",
  "react developer jobs",
  "nextjs developer jobs",
  "nodejs developer jobs",
  "javascript developer jobs",
  "typescript developer jobs",
  "python developer jobs",
  "java developer jobs",
  "php developer jobs",
  "mobile developer jobs",
  "android developer jobs",
  "ios developer jobs",
  "devops jobs",
  "cloud engineer jobs",
  "data engineer jobs",
  "data analyst jobs",
  "data scientist jobs",
  "machine learning jobs",
  "artificial intelligence jobs",
  "ai engineer jobs",
  "cybersecurity jobs",
  "cyber security careers",
  "network engineer jobs",
  "database administrator jobs",
  "qa engineer jobs",
  "software tester jobs",
  "ui ux designer jobs",
  "product designer jobs",
  "technical support jobs",
  "it support jobs",
  "information technology jobs",

  // Business & Management Jobs
  "business analyst jobs",
  "business development jobs",
  "business development manager jobs",
  "project manager jobs",
  "project management careers",
  "product manager jobs",
  "operations manager jobs",
  "operations jobs",
  "marketing jobs",
  "digital marketing jobs",
  "marketing manager jobs",
  "sales jobs",
  "sales manager jobs",
  "customer service jobs",
  "customer support jobs",
  "human resources jobs",
  "hr jobs",
  "hr manager jobs",
  "recruitment jobs",
  "recruiter jobs",
  "talent acquisition jobs",
  "administration jobs",
  "office administration jobs",
  "management jobs",
  "executive jobs",

  // Finance & Accounting Jobs
  "accounting jobs",
  "accountant jobs",
  "finance jobs",
  "finance manager jobs",
  "financial analyst jobs",
  "banking jobs",
  "banking careers",
  "audit jobs",
  "auditor jobs",
  "bookkeeper jobs",
  "bookkeeping jobs",
  "payroll jobs",
  "investment jobs",
  "insurance jobs",
  "financial services jobs",

  // Healthcare Jobs
  "healthcare jobs",
  "healthcare careers",
  "medical jobs",
  "medical careers",
  "nursing jobs",
  "nurse jobs",
  "pharmacy jobs",
  "pharmacist jobs",
  "hospital jobs",
  "clinical jobs",
  "healthcare administration jobs",
  "medical assistant jobs",
  "public health jobs",

  // Engineering Jobs
  "engineering jobs",
  "engineering careers",
  "civil engineering jobs",
  "mechanical engineering jobs",
  "electrical engineering jobs",
  "chemical engineering jobs",
  "industrial engineering jobs",
  "automotive engineering jobs",
  "construction jobs",
  "construction management jobs",
  "architect jobs",
  "architecture jobs",

  // Education Jobs
  "education jobs",
  "teaching jobs",
  "teacher jobs",
  "online teaching jobs",
  "remote teaching jobs",
  "university jobs",
  "school jobs",
  "academic jobs",
  "lecturer jobs",
  "professor jobs",
  "training jobs",
  "education careers",

  // Design & Creative Jobs
  "graphic designer jobs",
  "graphic design careers",
  "web designer jobs",
  "ui designer jobs",
  "ux designer jobs",
  "creative jobs",
  "content writer jobs",
  "content writing jobs",
  "copywriter jobs",
  "copywriting jobs",
  "technical writer jobs",
  "video editor jobs",
  "animation jobs",
  "creative director jobs",

  // Job Experience & Career Level
  "entry level jobs",
  "entry level career opportunities",
  "graduate jobs",
  "graduate career opportunities",
  "fresh graduate jobs",
  "jobs for fresh graduates",
  "junior level jobs",
  "mid level jobs",
  "senior level jobs",
  "senior professional jobs",
  "experienced professional jobs",
  "career opportunities for professionals",
  "jobs for experienced workers",
  "internship opportunities",
  "internship jobs",
  "paid internships",
  "student jobs",
  "jobs for students",
  "first job opportunities",
  "career starter jobs",

  // Employment Types
  "full time employment",
  "part time jobs",
  "part time employment",
  "contract jobs",
  "contract employment",
  "temporary jobs",
  "freelance jobs",
  "freelancing opportunities",
  "permanent jobs",
  "permanent employment",
  "seasonal jobs",
  "internship opportunities worldwide",
  "on site jobs",
  "hybrid jobs",
  "flexible jobs",

  // Career Search Intent
  "search jobs online",
  "find employment online",
  "find international employment",
  "find remote employment",
  "find career opportunities",
  "search international jobs",
  "search remote jobs",
  "search jobs worldwide",
  "best jobs worldwide",
  "best international jobs",
  "top career opportunities",
  "latest career opportunities",
  "new job opportunities",
  "new jobs worldwide",
  "daily job openings",
  "latest job openings",
  "current job openings",
  "international job openings",
  "remote job openings",
  "global employment opportunities",
  "worldwide employment opportunities",

  // Hiring & Recruitment
  "global hiring",
  "international hiring",
  "worldwide hiring",
  "online recruitment",
  "international recruitment",
  "global recruitment",
  "remote recruitment",
  "international employers",
  "global employers",
  "remote employers",
  "job vacancies worldwide",
  "international vacancies",
  "remote vacancies",
  "job openings worldwide",
  "career openings",
  "employment vacancies",
  "hiring opportunities",
  "career openings worldwide",
  "global workforce opportunities",
  "international workforce jobs",

  // Visa & Relocation
  "jobs with visa sponsorship",
  "visa sponsored employment",
  "employer sponsored jobs",
  "work visa jobs",
  "work permit jobs",
  "jobs abroad with sponsorship",
  "international jobs with sponsorship",
  "relocation jobs",
  "jobs with relocation assistance",
  "international relocation careers",
  "overseas employment",
  "overseas jobs",
  "overseas career opportunities",
  "jobs for foreigners",
  "jobs for international workers",
  "expat jobs",
  "expat career opportunities",

  // General Career Keywords
  "career jobs",
  "career search",
  "career website",
  "career platform",
  "employment website",
  "online job search",
  "job search platform",
  "job listing website",
  "job listings online",
  "employment listings",
  "career listings",
  "job opportunities online",
  "employment opportunities worldwide",
  "professional opportunities",
  "professional careers",
  "career development opportunities",
  "career growth opportunities",
  "career advancement jobs",
  "professional job opportunities",
  "global career platform",
];